version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: grafana
      MYSQL_DATABASE: transactions
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana-pw
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - grafana-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    depends_on:
      - mariadb
    networks:
      - grafana-network
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  grafana-network:
    driver: bridge

volumes:
  mariadb-data:
  grafana-data:
