{
 "title": "Expenses - Conjunta",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "€ spent per month",
   "type": "barchart",
   "description": "Total spent per month (without mortgage early down-payments)",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "WITH monthly_sums AS (\n    SELECT \n        YEAR(date) AS year,\n        MONTHNAME(date) AS month,\n        SUM(debit) AS total_debit\n    FROM \n        transactions\n    WHERE \n        debit IS NOT NULL and subcategory <> \"Amortização\"\n    GROUP BY \n        YEAR(date), MONTH(date)\n)\nSELECT \n    month,\n    AVG(total_debit) AS average_monthly_debit\nFROM \n    monthly_sums\nGROUP BY \n    month\nORDER BY \n    FIELD(month, 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');\n"
    }
   ]
  },
  {
   "title": "Top 5 expense categories",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT category, SUM(debit) AS total_debit\nFROM grafana.transactions\nWHERE debit IS NOT NULL\nGROUP BY category\nORDER BY total_debit DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Top 5 expenses of all time",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 6 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select CONCAT(description, \" - \", \"€\", debit) as alias from grafana.transactions where debit is not null order by debit desc limit 5"
    }
   ]
  },
  {
   "title": "€ spent in groceries per month",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "WITH monthly_sums AS (\n    SELECT \n        YEAR(date) AS year,\n        MONTHNAME(date) AS month,\n        SUM(debit) AS total_debit\n    FROM \n        transactions\n    WHERE \n        debit IS NOT NULL AND category = 'groceries'\n    GROUP BY \n        YEAR(date), MONTH(date)\n)\nSELECT \n    month,\n    AVG(total_debit) AS average_monthly_debit\nFROM \n    monthly_sums\nGROUP BY \n    month\nORDER BY \n    FIELD(month, 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');\n"
    }
   ]
  },
  {
   "title": "Favorite restaurant",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select sum(debit) as \"Total\", subcategory as Restaurante from grafana.transactions where category ='Restauração' group by subcategory order by Total desc limit 1"
    }
   ]
  },
  {
   "title": "Average € spent per category per month",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "WITH monthly_category_sums AS (\n    SELECT \n        category,\n        YEAR(date) AS year,\n        MONTH(date) AS month,\n        SUM(debit) AS total_debit\n    FROM \n        transactions\n    WHERE \n        debit IS NOT NULL and subcategory <> \"Amortização\"\n    GROUP BY \n        category, YEAR(date), MONTH(date)\n)\nSELECT \n    category,\n    AVG(total_debit) AS average_monthly_debit\nFROM \n    monthly_category_sums\nGROUP BY \n    category;\n"
    }
   ]
  },
  {
   "title": "Average € spent with cars per month",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "WITH first_and_last_dates AS (\n    SELECT \n        MIN(date) AS first_date,\n        MAX(date) AS last_date\n    FROM \n        transactions\n    WHERE \n        category = 'Carro'\n), \ntotal_spent_per_subcategory AS (\n    SELECT \n        subcategory,\n        SUM(debit) AS total_spent\n    FROM \n        transactions\n    WHERE \n        category = 'Carro'\n    GROUP BY \n        subcategory\n),\nmonths_between AS (\n    SELECT \n        TIMESTAMPDIFF(MONTH, first_date, last_date) + 1 AS months\n    FROM \n        first_and_last_dates\n)\nSELECT \n    subcategory,\n    total_spent / months AS average_monthly_spent\nFROM \n    total_spent_per_subcategory, months_between;\n"
    }
   ]
  }
 ]
}