{
 "title": "Expenses - Conta Conjunta",
 "time": { "from": "2022-08-01", "to": "now" },
 "panels": [
  {
   "title": "Total spent on the last 12 months",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "transactions",
     "rawSql": "SELECT \n    DATE_FORMAT(date, '%m/%Y') AS month,\n    SUM(debit) AS total_spent\nFROM \n    transactions\nWHERE \n    date >= DATE_FORMAT(DATE_SUB(CURRENT_DATE(), INTERVAL 13 MONTH), '%Y-%m-01')\n    AND date < DATE_FORMAT(CURRENT_DATE(), '%Y-%m-01')\n    AND debit IS NOT NULL\n    AND subcategory <> \"Amortização\"\nGROUP BY \n    DATE_FORMAT(date, '%m/%Y'), YEAR(date), MONTH(date)\nORDER BY \n    YEAR(date), MONTH(date);"
    }
   ]
  },
  {
   "title": "Top 5 expense categories",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT category, SUM(debit) AS total_debit\nFROM transactions\nWHERE debit IS NOT NULL\nGROUP BY category\nORDER BY total_debit DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Favorite restaurant",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select sum(debit) as \"Total\", subcategory as Restaurante from transactions where category ='Restauração' group by subcategory order by Total desc limit 1"
    }
   ]
  },
  {
   "title": "€ spent per month (excl. vacations)",
   "type": "barchart",
   "description": "Total spent per month (without mortgage early down-payments)",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n    DATE_FORMAT(date, '%b %Y') AS month_year,\n    SUM(debit) AS total_debit\nFROM \n    transactions\nWHERE \n    $__timeFilter(date)\n    AND debit IS NOT NULL\n    AND category <> \"Férias\"\n    AND subcategory <> \"Amortização\"\nGROUP BY \n    YEAR(date), MONTH(date)\nORDER BY \n    YEAR(date), MONTH(date);"
    }
   ]
  },
  {
   "title": "Top 10 expenses of all time",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 14, "y": 10 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "select CONCAT(description, \" - \", \"€\", debit) as alias from transactions where debit is not null order by debit desc limit 10"
    }
   ]
  },
  {
   "title": "€ spent in groceries per month",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n    DATE_FORMAT(date, '%b %Y') AS month_year,\n    SUM(debit) AS total_debit\nFROM \n    transactions\nWHERE \n    $__timeFilter(date)\n    AND debit IS NOT NULL \n    AND category = 'groceries'\nGROUP BY \n    YEAR(date), MONTH(date)\nORDER BY \n    YEAR(date), MONTH(date);"
    }
   ]
  },
  {
   "title": "Average € spent per category per month (excl. vacations)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "WITH monthly_category_sums AS (\n    SELECT \n        category,\n        YEAR(date) AS year,\n        MONTH(date) AS month,\n        SUM(debit) AS total_debit\n    FROM \n        transactions\n    WHERE \n        $__timeFilter(date)\n        AND debit IS NOT NULL\n        AND category <> \"Férias\"\n        AND subcategory <> \"Amortização\"\n    GROUP BY \n        category, YEAR(date), MONTH(date)\n)\nSELECT \n    category,\n    AVG(total_debit) AS value\nFROM \n    monthly_category_sums\nGROUP BY \n    category\nORDER BY \n    value DESC;"
    }
   ]
  },
  {
   "title": "Average € spent with cars per month",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "WITH RECURSIVE date_range AS (\n    SELECT \n        DATE_FORMAT(\n            DATE_ADD(\n                DATE_FORMAT($__timeFrom(), '%Y-%m-01'),\n                INTERVAL 0 MONTH\n            ),\n            '%Y-%m-01'\n        ) AS month_date\n    UNION ALL\n    SELECT \n        DATE_ADD(month_date, INTERVAL 1 MONTH)\n    FROM \n        date_range\n    WHERE \n        month_date < DATE_FORMAT($__timeTo(), '%Y-%m-01')\n),\nmonthly_spending AS (\n    SELECT \n        DATE_FORMAT(date, '%Y-%m-01') AS month_date,\n        SUM(debit) AS total_spent\n    FROM \n        transactions\n    WHERE \n        $__timeFilter(date)\n        AND category = 'Carro'\n        AND debit IS NOT NULL\n    GROUP BY \n        DATE_FORMAT(date, '%Y-%m-01')\n)\nSELECT \n    UNIX_TIMESTAMP(dr.month_date) AS time_sec,\n    COALESCE(ms.total_spent, 0) AS total_spent\nFROM \n    date_range dr\nLEFT JOIN \n    monthly_spending ms ON dr.month_date = ms.month_date\nORDER BY \n    dr.month_date;"
    }
   ]
  },
  {
   "title": "€ spent per year",
   "type": "barchart",
   "description": "Total spent per year (without mortgage early down-payments)",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "grafana",
     "rawSql": "SELECT \n    CAST(YEAR(date) AS CHAR) AS year,\n    SUM(debit) AS total_debit\nFROM \n    transactions\nWHERE \n    $__timeFilter(date)\n    AND debit IS NOT NULL\n    AND subcategory <> \"Amortização\"\nGROUP BY \n    YEAR(date)\nORDER BY \n    YEAR(date);"
    }
   ]
  }
 ]
}